const api = {
    home: {path: '/',name: 'home'},
    order: {path:'/user/order', name: 'order'},
    orderDetail: {path: '/business/order/details', name : 'order detail'},
    search: {path:'/user/search', name: 'search'},
    profile: {path: '/user/profile', name: 'profile'},
    profileEdit: {path: '/user/profileEdit', name: 'profileEdit'},
    blacklist: {path: '/user/blacklist', name: 'blacklist'},
    productDetails: {path: '/product/detail', name: 'product detail'},
    productComments: {path: '/product/comments', name: 'product comments'},
    shoppingCart: {path: '/user/shoppingCart', name: 'shopping card'},
    purchase: {path: '/user/purchase', name: 'purchase'},
    rate: {path: '/user/rate', name: 'rate'},
    shop: {path: '/shop', name: 'shop'},
    login: {path: '/login', name: 'login'},
    register: {path: '/register', name: 'register'},
    reSetPassword: {path: '/reset_password', name: 'reSetPassword'}
}

export const netApi = {
    login:{path: '/user/login', },
    register:{path: '/user/register', },
    info:{path: '/user/info', },
    update: [
        {name: 'account',path: '/user/update/account'},
        {name: 'nickname',path: '/user/update/nickname'},
        {name: 'password',path: '/user/update/password'},
        {name: 'avatar',path: '/user/update/avatar'},
        {name: 'email',path: '/user/update/email'},
        {name: 'phone', path: '/user/update/phone'},
    ],
    reSetPassword: {path: 'user/rest/password'},
    recommend: {path: '/product/recommend/'},
    location: {path: 'shop/location'},
    getProduct: {path: '/product/get/'},
    productPicture: {path: 'product/picture/list/'},
    productComments: {path: 'product/comments/'},
    getPrice: {path: 'product/get/price'},
    shopShowInfo: {path: 'shop/'},
    saleProduct: {path: 'shop/sale/'},
    getOrder: {path: 'product/payment/order'},
    addCart: {path: 'cart/add'},
    getCart: {path: 'cart/get'},
    removeFromCart: {path: 'cart/remove'},
    orderInfo: {path: 'order/info/'},
    orderCancel : {path: 'order/cancel'},
    orderFinish: {path: 'order/finish'},
    goodsRate: {path: 'product/rate'},
}
export default api